version: '3'
services:
 fluentd:
  image: fluent/fluentd:v1.6-debian-1
  volumes:
    - ./fluentd/conf:/fluentd/conf
  links:
    - "elasticsearch"
  ports:
    - "24224:24224"
    - "24224:24224/udp"
 
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
  environment:
    - "discovery.type=single-node"
  expose:
    - "9200"
  ports:
    - "9200:9200"
